config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :guests
  
  resources :guests, only: :none do
    resource :profile
  end

  root 'home#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :guest

  mount_uploader :avatar, AvatarUploader
  
  validates_presence_of :name
  validates_presence_of :bio
  validates_presence_of :guest_id

  def avatar_url
    self.avatar.try(:url) || 'default-profile-picture.png'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  alias_method :current_user, :current_guest

  rescue_from Pundit::NotAuthorizedError, with: :guest_not_authorized

  private

  def guest_not_authorized
    flash[:alert] = "Oops, you are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_guest
    before_action :set_profile, except: [:new, :create]
    before_action :authenticate_guest!

    def show
    end

    def edit
        authorize @profile
    end

    def update
        if @profile.update_attributes! profile_params
            flash[:notice] = "Profile updated!"
        else
            flash[:error] = "Error while updating profile: #{@profile.errors}"
        end
        redirect_to edit_guest_profile_url @guest
        authorize @profile
    end

    def new
        @profile = @guest.build_profile
        authorize @profile
    end 

    def create
        @profile = @guest.create_profile(profile_params)
        authorize @profile
        
        respond_to do |format|
            if @profile.save
                format.html { redirect_to root_path, notice: "Profile was successfully created." }
            else
                format.html { render :new }
                format.json { render json: @profile.errors, status: :unprocessable_entity }
            end
        end
    end

    private

    def profile_params
        params.require(:profile).permit(:avatar, :name, :bio, :guest_id, :phone, :address, :zipcode)
    end 

    def set_guest
        @guest = Guest.find(params[:guest_id])
    end

    def set_profile
        @profile = @guest.profile
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/guests/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/home/index.html.haml
.container-fluid
  %h1 
    %span.cc-red ComfortCrib 
    Book age approiate kid friendly places and start enjoying your stay.

app/views/layouts/_main_nav.html.haml
%nav.navbar.navbar-static-top
  .container-fluid
    .navbar-header
      %a.navbar-brand{href: root_path}
        ComfortCrib
    %ul.nav.navbar-nav.navbar-right
      %li
        = link_to 'Become a Host', root_path
      %li
        = link_to 'Help', root_path
      - unless signed_in?
        %li
          = link_to 'Sign up', new_guest_registration_path
        %li 
          = link_to 'Log in', new_guest_session_path
      - else 
        %li
          = link_to 'My Account', edit_guest_profile_path(current_guest)
        %li 
          = link_to 'Log out', destroy_guest_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ComfortCrib
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/main_nav'
    - unless notice.nil?
      .notice.alert.alert-success
        = notice
    - unless alert.nil?
      .alert.alert-danger
        = alert
    = yield

app/views/profiles/_form.html.haml
= f.label :avatar
%br/
= image_tag @guest.profile.avatar_url, height: '200', width: '200', class: ''
= f.file_field :avatar
%br/
= f.label :name
= f.text_field :name, :required => true, class: 'form-control'
%br/
= f.label :bio 
= f.text_area :bio, :required => true, class: 'form-control'
%br/
= f.label :phone
= f.telephone_field :phone, class: 'form-control'
%br/
= f.label :address
= f.text_field :address, class: 'form-control'
%br/
= f.label :zipcode
= f.number_field :zipcode, class: 'form-control'
%br/
= f.submit "Submit", class: 'cc-btn-primary btn btn-lg'

app/views/profiles/edit.html.haml
.container-fluid
  .col-sm-5.col-center
    %h2.text-center Edit Profile

    = form_for @profile, url: guest_profile_path(@guest) do |f|

      - if @profile.errors.any?
        #error_explanation
          %h2 Oops! We couldn't edit your profile. Please see below.
          %ul 
            - @profile.errors.full_messages.each do |message|
              %li 
                = message
    
      = render partial: 'profiles/form', locals: {f: f}

app/views/profiles/new.html.haml
.container-fluid
  .col-sm-5.col-center
    Create a new Profile

    = form_for @profile, url: guest_profile_path(@guest) do |f|

      - if @profile.errors.any?
        #error_explanation
          %h2 Oops! We couldn't create your profile. Please see below.
          %ul 
            - @profile.errors.full_messages.each do |message|
              %li 
                = message
    
      = f.label :avatar
      = f.file_field :avatar, class: 'form-control'

      = f.label :name
      = f.text_field :name, :required => true, class: 'form-control'

      = f.label :bio 
      = f.text_area :bio, :required => true, class: 'form-control'

      = f.label :phone
      = f.telephone_field :phone, class: 'form-control'

      = f.label :address
      = f.text_field :address, class: 'form-control'

      = f.label :zipcode
      = f.number_field :zipcode, class: 'form-control'

      = f.submit "Create", class: 'cc-btn-primary btn btn-lg'

app/views/profiles/show.html.haml
.container-fluid
  .col-sm-5.col-center.text-center
    = image_tag @profile.avatar_url, height: '200', width: '200', class: 'img-circle center'
    %h2
      = @profile.name

    %h4
      = @profile.bio
    %p
      = @profile.phone
    %p
      = @profile.address
    %p
      = @profile.zipcode